export type BrazilianBank = { code: string; name: string };

/** Bancos mais usados em contas de recebedores (COMPE). */
export const BRAZILIAN_BANKS: BrazilianBank[] = [
  { code: "001", name: "Banco do Brasil" },
  { code: "003", name: "Banco da Amazônia" },
  { code: "004", name: "Banco do Nordeste" },
  { code: "007", name: "BNDES" },
  { code: "010", name: "Credicoamo" },
  { code: "011", name: "Credit Suisse" },
  { code: "012", name: "Banco Inbursa" },
  { code: "014", name: "State Street BR" },
  { code: "015", name: "UBS Brasil" },
  { code: "016", name: "Coop de Crédito Mútuo" },
  { code: "017", name: "BNY Mellon Banco" },
  { code: "021", name: "Banestes" },
  { code: "024", name: "Banco Bandepe" },
  { code: "025", name: "Banco Alfa" },
  { code: "029", name: "Banco Itaú Consignado" },
  { code: "033", name: "Santander" },
  { code: "036", name: "Banco Bradesco BBI" },
  { code: "037", name: "Banco do Estado do Pará" },
  { code: "040", name: "Banco Cargill" },
  { code: "041", name: "Banrisul" },
  { code: "047", name: "Banco do Estado de Sergipe" },
  { code: "060", name: "Confidence" },
  { code: "062", name: "Hipercard" },
  { code: "063", name: "Banco Bradescard" },
  { code: "064", name: "Goldman Sachs" },
  { code: "065", name: "Banco Andbank" },
  { code: "066", name: "Banco Morgan Stanley" },
  { code: "069", name: "Banco Crefisa" },
  { code: "070", name: "BRB" },
  { code: "074", name: "Safra" },
  { code: "075", name: "Banco ABN AMRO" },
  { code: "076", name: "Banco KDB" },
  { code: "077", name: "Banco Inter" },
  { code: "078", name: "Haitong" },
  { code: "079", name: "Banco Original do Agronegócio" },
  { code: "081", name: "BancoSeguro" },
  { code: "082", name: "Banco Topázio" },
  { code: "083", name: "Banco da China Brasil" },
  { code: "084", name: "Uniprime Norte do Paraná" },
  { code: "085", name: "Ailos" },
  { code: "089", name: "Credisan" },
  { code: "091", name: "Unicred Central RS" },
  { code: "092", name: "BRK" },
  { code: "093", name: "Pólocred" },
  { code: "094", name: "Banco Finaxis" },
  { code: "095", name: "Travelex" },
  { code: "096", name: "Banco B3" },
  { code: "097", name: "Credisis" },
  { code: "098", name: "Credialiança" },
  { code: "099", name: "Uniprime Central" },
  { code: "100", name: "Planner" },
  { code: "101", name: "Renascença" },
  { code: "102", name: "XP Investimentos" },
  { code: "104", name: "Caixa Econômica Federal" },
  { code: "107", name: "Banco Bocom BBM" },
  { code: "108", name: "PortoCred" },
  { code: "111", name: "Oliveira Trust" },
  { code: "113", name: "Magliano" },
  { code: "114", name: "Central Cooperativa de Crédito" },
  { code: "119", name: "Banco Western Union" },
  { code: "120", name: "Banco Rodobens" },
  { code: "121", name: "Banco Agibank" },
  { code: "122", name: "Banco Bradesco BERJ" },
  { code: "124", name: "Banco Woori" },
  { code: "125", name: "Brasil Plural" },
  { code: "126", name: "BR Partners" },
  { code: "127", name: "Codepe" },
  { code: "128", name: "MS Bank" },
  { code: "129", name: "UBS Brasil BI" },
  { code: "130", name: "Caruana" },
  { code: "131", name: "Tullett Prebon" },
  { code: "132", name: "ICBC do Brasil" },
  { code: "133", name: "Cresol" },
  { code: "134", name: "BGC Liquidez" },
  { code: "136", name: "Unicred Cooperativa" },
  { code: "138", name: "Get Money" },
  { code: "139", name: "Intesa Sanpaolo" },
  { code: "140", name: "Easynvest" },
  { code: "142", name: "Broker Brasil" },
  { code: "143", name: "Treviso" },
  { code: "144", name: "Bexs" },
  { code: "145", name: "Levycam" },
  { code: "146", name: "Guitta" },
  { code: "149", name: "Facta Financeira" },
  { code: "157", name: "ICAP do Brasil" },
  { code: "159", name: "Casa do Crédito" },
  { code: "163", name: "Commerzbank" },
  { code: "169", name: "Banco Olé Bonsucesso" },
  { code: "173", name: "BRL Trust" },
  { code: "174", name: "Pernambucanas Financiadora" },
  { code: "177", name: "Guide Investimentos" },
  { code: "180", name: "CM Capital Markets" },
  { code: "183", name: "Socred" },
  { code: "184", name: "Banco Itaú BBA" },
  { code: "188", name: "Ativa Investimentos" },
  { code: "189", name: "HS Financeira" },
  { code: "190", name: "Servicoop" },
  { code: "191", name: "Nova Futura" },
  { code: "194", name: "Parmetal" },
  { code: "196", name: "Fair" },
  { code: "197", name: "Stone Pagamentos" },
  { code: "208", name: "Banco BTG Pactual" },
  { code: "212", name: "Banco Original" },
  { code: "213", name: "Arbi" },
  { code: "217", name: "Banco John Deere" },
  { code: "218", name: "Banco BS2" },
  { code: "222", name: "Banco Credit Agricole" },
  { code: "224", name: "Banco Fibra" },
  { code: "233", name: "Banco Cifra" },
  { code: "237", name: "Bradesco" },
  { code: "241", name: "Banco Clássico" },
  { code: "243", name: "Banco Máxima" },
  { code: "246", name: "Banco ABC Brasil" },
  { code: "249", name: "Banco Investcred Unibanco" },
  { code: "250", name: "BCV" },
  { code: "253", name: "Bexs Corretora de Câmbio" },
  { code: "254", name: "Paraná Banco" },
  { code: "259", name: "Moneycorp" },
  { code: "260", name: "Nubank" },
  { code: "265", name: "Banco Fator" },
  { code: "266", name: "Banco Cédula" },
  { code: "268", name: "Barigui" },
  { code: "269", name: "HSBC Brasil" },
  { code: "270", name: "Sagitur" },
  { code: "272", name: "AGK Corretora" },
  { code: "273", name: "Cooperativa de Crédito Rural" },
  { code: "274", name: "Money Plus" },
  { code: "276", name: "Senff" },
  { code: "278", name: "Genial Investimentos" },
  { code: "279", name: "Cooperativa de Crédito Rural de Primavera" },
  { code: "280", name: "Avista" },
  { code: "281", name: "Cooperativa de Crédito Rural Coopavel" },
  { code: "283", name: "RB Capital Investimentos" },
  { code: "285", name: "Frente Corretora" },
  { code: "286", name: "Cooperativa de Crédito Rural de Ouro" },
  { code: "288", name: "Carol DTVM" },
  { code: "289", name: "DECYSEO" },
  { code: "290", name: "PagSeguro" },
  { code: "292", name: "BS2 Distribuidora" },
  { code: "293", name: "Lastro RDV" },
  { code: "296", name: "Vision" },
  { code: "298", name: "Vip's" },
  { code: "299", name: "Sorocred" },
  { code: "300", name: "Banco de La Nacion Argentina" },
  { code: "301", name: "BPP Instituição de Pagamento" },
  { code: "306", name: "Portopar" },
  { code: "307", name: "Terra Investimentos" },
  { code: "309", name: "Cambionet" },
  { code: "310", name: "Vortx DTVM" },
  { code: "311", name: "Dourada Corretora" },
  { code: "312", name: "HSCM SCMEPP" },
  { code: "313", name: "Amazônia Corretora" },
  { code: "315", name: "PI Distribuidora" },
  { code: "318", name: "Banco BMG" },
  { code: "319", name: "Omni Banco" },
  { code: "320", name: "China Construction Bank" },
  { code: "321", name: "Crefaz" },
  { code: "322", name: "Cooperativa de Crédito Rural de Abelardo Luz" },
  { code: "323", name: "Mercado Pago" },
  { code: "324", name: "Cartos" },
  { code: "325", name: "Órama Investimentos" },
  { code: "326", name: "Parati Crédito" },
  { code: "328", name: "Cooperativa de Crédito Rural de São Miguel" },
  { code: "329", name: "QI Sociedade de Crédito" },
  { code: "330", name: "Banco Bari" },
  { code: "331", name: "Fram Capital" },
  { code: "332", name: "Acesso Soluções de Pagamento" },
  { code: "335", name: "Banco Digio" },
  { code: "336", name: "C6 Bank" },
  { code: "341", name: "Itaú Unibanco" },
  { code: "342", name: "Creditas" },
  { code: "343", name: "FFA Sociedade de Crédito" },
  { code: "348", name: "Banco XP" },
  { code: "349", name: "AL5" },
  { code: "350", name: "Cooperativa de Crédito Rural de Primavera do Leste" },
  { code: "352", name: "Toro Corretora" },
  { code: "354", name: "Necton Investimentos" },
  { code: "355", name: "Ótimo Sociedade de Crédito" },
  { code: "356", name: "Realize Crédito" },
  { code: "358", name: "Midway" },
  { code: "359", name: "Zema Crédito" },
  { code: "360", name: "Trinus Capital" },
  { code: "362", name: "Cielo" },
  { code: "363", name: "Socopa" },
  { code: "364", name: "Gerencianet" },
  { code: "365", name: "Solidus" },
  { code: "366", name: "Banco Société Générale Brasil" },
  { code: "367", name: "Vitreo" },
  { code: "368", name: "Banco CSF" },
  { code: "370", name: "Banco Mizuho" },
  { code: "371", name: "Warren" },
  { code: "373", name: "UP.P" },
  { code: "374", name: "Realize Crédito" },
  { code: "376", name: "Banco J.P. Morgan" },
  { code: "377", name: "BMS Sociedade de Crédito" },
  { code: "378", name: "BBC Leasing" },
  { code: "379", name: "Cooperativa de Crédito Rural de Primavera do Leste" },
  { code: "380", name: "PicPay" },
  { code: "381", name: "Banco Mercedes-Benz" },
  { code: "382", name: "Fidúcia" },
  { code: "383", name: "Juno" },
  { code: "384", name: "Global SCM" },
  { code: "385", name: "Cooperativa de Crédito Rural de Ibiam" },
  { code: "386", name: "Nu Financeira" },
  { code: "387", name: "Banco Toyota" },
  { code: "388", name: "Banco Mercantil do Brasil" },
  { code: "389", name: "Banco Mercantil do Brasil" },
  { code: "390", name: "Banco GM" },
  { code: "391", name: "Cooperativa de Crédito Rural de Ibiam" },
  { code: "393", name: "Banco Volkswagen" },
  { code: "394", name: "Banco Bradesco Financiamentos" },
  { code: "395", name: "F.D'Gold" },
  { code: "396", name: "HUB Pagamentos" },
  { code: "397", name: "Listo" },
  { code: "398", name: "Ideal Corretora" },
  { code: "399", name: "Kirton Bank" },
  { code: "403", name: "Cora" },
  { code: "404", name: "Sumup" },
  { code: "406", name: "Accredito" },
  { code: "407", name: "Íon" },
  { code: "408", name: "Bónuscred" },
  { code: "410", name: "Planner Sociedade de Crédito" },
  { code: "411", name: "Via Certa Financiadora" },
  { code: "412", name: "Banco Capital" },
  { code: "413", name: "Banco BV" },
  { code: "414", name: "Lend" },
  { code: "416", name: "Lamara" },
  { code: "418", name: "Zipdin" },
  { code: "419", name: "Numbrs" },
  { code: "421", name: "Lar Cooperativa de Crédito" },
  { code: "422", name: "Safra" },
  { code: "423", name: "Coluna" },
  { code: "425", name: "Socinal" },
  { code: "426", name: "Biorc Financeira" },
  { code: "427", name: "Cred-UFES" },
  { code: "428", name: "Credsystem" },
  { code: "429", name: "Crediare" },
  { code: "430", name: "Cooperativa de Crédito Rural de São Miguel do Oeste" },
  { code: "433", name: "BR-Capital" },
  { code: "435", name: "Delbank" },
  { code: "438", name: "Trustee" },
  { code: "439", name: "ID Corretora" },
  { code: "440", name: "Credihome" },
  { code: "442", name: "Magnetis" },
  { code: "443", name: "Credihome" },
  { code: "444", name: "Trinus" },
  { code: "445", name: "Plantae" },
  { code: "447", name: "Mirae Asset" },
  { code: "448", name: "Hemera" },
  { code: "449", name: "DM" },
  { code: "450", name: "Fitbank" },
  { code: "451", name: "J17" },
  { code: "452", name: "Credifit" },
  { code: "453", name: "Banco Rural" },
  { code: "454", name: "Méliuz" },
  { code: "455", name: "Fênix" },
  { code: "456", name: "Banco MUFG Brasil" },
  { code: "457", name: "UY3" },
  { code: "458", name: "Hedge Investments" },
  { code: "459", name: "Cooperativa de Crédito Rural de Primavera do Leste" },
  { code: "460", name: "Unavanti" },
  { code: "461", name: "Asaas" },
  { code: "462", name: "Stark Bank" },
  { code: "463", name: "Azumi" },
  { code: "464", name: "Banco Sumitomo Mitsui" },
  { code: "465", name: "Capital Consig" },
  { code: "466", name: "Banco Mitsubishi UFJ" },
  { code: "467", name: "Master" },
  { code: "468", name: "Portoseg" },
  { code: "469", name: "Liga" },
  { code: "470", name: "CDC" },
  { code: "471", name: "Banco Caixa Geral Brasil" },
  { code: "473", name: "Banco Caixa Geral Brasil" },
  { code: "475", name: "Banco Yamaha Motor" },
  { code: "477", name: "Citibank" },
  { code: "478", name: "GazinCred" },
  { code: "479", name: "Banco ItauBank" },
  { code: "481", name: "Superlógica" },
  { code: "482", name: "SBCash" },
  { code: "484", name: "MAF" },
  { code: "487", name: "Deutsche Bank" },
  { code: "488", name: "JPMorgan Chase Bank" },
  { code: "492", name: "ING Bank" },
  { code: "494", name: "Banco Rep Oriental Uruguay" },
  { code: "495", name: "Banco La Provincia de Buenos Aires" },
  { code: "496", name: "BBVA Brasil" },
  { code: "497", name: "Banco Hispano Americano" },
  { code: "498", name: "Centro Hispano Banco" },
  { code: "499", name: "Banco de La Republica Oriental del Uruguay" },
  { code: "502", name: "Santander" },
  { code: "505", name: "Banco Credit Suisse" },
  { code: "600", name: "Banco Luso Brasileiro" },
  { code: "604", name: "Banco Industrial do Brasil" },
  { code: "610", name: "Banco VR" },
  { code: "611", name: "Banco Paulista" },
  { code: "612", name: "Banco Guanabara" },
  { code: "613", name: "Omni Banco" },
  { code: "623", name: "Banco Pan" },
  { code: "626", name: "Banco Ficsa" },
  { code: "630", name: "Banco Smartbank" },
  { code: "633", name: "Banco Rendimento" },
  { code: "634", name: "Banco Triângulo" },
  { code: "637", name: "Banco Sofisa" },
  { code: "641", name: "Banco Alvorada" },
  { code: "643", name: "Banco Pine" },
  { code: "652", name: "Itaú Unibanco Holding" },
  { code: "653", name: "Banco Indusval" },
  { code: "654", name: "Banco A.J. Renner" },
  { code: "655", name: "Banco Votorantim" },
  { code: "707", name: "Banco Daycoval" },
  { code: "712", name: "Banco Ourinvest" },
  { code: "720", name: "Banco Maxinvest" },
  { code: "739", name: "Banco Cetelem" },
  { code: "741", name: "Banco Ribeirão Preto" },
  { code: "743", name: "Banco Semear" },
  { code: "745", name: "Citibank" },
  { code: "746", name: "Banco Modal" },
  { code: "747", name: "Banco Rabobank" },
  { code: "748", name: "Sicredi" },
  { code: "751", name: "Scotiabank Brasil" },
  { code: "752", name: "Banco BNP Paribas Brasil" },
  { code: "753", name: "Novo Banco Continental" },
  { code: "754", name: "Banco Sistema" },
  { code: "755", name: "Bank of America Merrill Lynch" },
  { code: "756", name: "Sicoob" },
  { code: "757", name: "Banco KEB Hana do Brasil" },
];

export const BRAZILIAN_BANK_CODE_SET = new Set(BRAZILIAN_BANKS.map(bank => bank.code));

const digits = (value: string) => value.replace(/\D/g, "");

export function normalizeBankCode(value: string): string {
  return digits(value).padStart(3, "0").slice(-3);
}

export function getBankLabel(code: string): string | null {
  const normalized = normalizeBankCode(code);
  return BRAZILIAN_BANKS.find(bank => bank.code === normalized)?.name ?? null;
}

export function isValidBankCode(value: string): boolean {
  return BRAZILIAN_BANK_CODE_SET.has(normalizeBankCode(value));
}

export function validateBankAccount(input: {
  bank_code: string;
  branch_number: string;
  branch_check_digit?: string;
  account_number: string;
  account_check_digit: string;
}): string | null {
  const bankCode = normalizeBankCode(input.bank_code);
  if (!isValidBankCode(bankCode)) {
    return `Selecione um banco válido (código ${bankCode || "—"}).`;
  }

  const branch = digits(input.branch_number);
  if (!/^\d{1,5}$/.test(branch)) return "Agência deve ter entre 1 e 5 dígitos.";

  if (input.branch_check_digit) {
    const branchDigit = digits(input.branch_check_digit);
    if (!/^\d{0,2}$/.test(branchDigit)) return "Dígito da agência inválido.";
  }

  const account = digits(input.account_number);
  if (!/^\d{1,13}$/.test(account)) return "Conta deve ter entre 1 e 13 dígitos.";

  const accountDigit = String(input.account_check_digit || "").trim().toUpperCase();
  if (!/^[0-9X]{1,2}$/.test(accountDigit)) return "Dígito da conta inválido (número ou X).";

  return null;
}
