// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar produtos",
  description: "Lista os produtos ativos do restaurante do usu\xE1rio logado, com nome, pre\xE7o e categoria.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Quantidade m\xE1xima de produtos (padr\xE3o 20)."),
    search: z.string().optional().describe("Termo para filtrar por nome do produto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit = 20, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("products").select("id, name, description, price, is_active, category:categories(id, name)").eq("is_active", true).order("name", { ascending: true }).limit(limit);
    if (search) {
      query = query.ilike("name", `%${search}%`);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length > 0 ? JSON.stringify(data, null, 2) : "Nenhum produto encontrado."
        }
      ],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista as categorias do card\xE1pio do restaurante do usu\xE1rio logado, ordenadas por posi\xE7\xE3o.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Quantidade m\xE1xima de categorias (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit = 50 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("categories").select("id, name, order_position, created_at").order("order_position", { ascending: true, nullsFirst: false }).order("name", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length > 0 ? JSON.stringify(data, null, 2) : "Nenhuma categoria encontrada."
        }
      ],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_orders_default = defineTool3({
  name: "list_orders",
  title: "Listar pedidos recentes",
  description: "Lista os pedidos mais recentes do restaurante do usu\xE1rio logado, com status e valor total.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Quantidade m\xE1xima de pedidos (padr\xE3o 20)."),
    status: z3.string().optional().describe("Filtrar por status (ex.: pending, preparing, ready, delivered, cancelled).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit = 20, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let query = supabaseForUser3(ctx).from("orders").select("id, order_number, customer_name, status, payment_status, total, order_type, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) {
      query = query.eq("status", status);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length > 0 ? JSON.stringify(data, null, 2) : "Nenhum pedido encontrado."
        }
      ],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order-details.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.4";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_order_details_default = defineTool4({
  name: "get_order_details",
  title: "Detalhes do pedido",
  description: "Retorna os detalhes completos de um pedido, incluindo itens, observa\xE7\xF5es e dados do cliente.",
  inputSchema: {
    order_id: z4.string().uuid().describe("ID do pedido (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("orders").select(
      "id, order_number, customer_name, customer_email, customer_phone, status, payment_status, total, order_type, source, created_at, updated_at, order_items(id, product_name, quantity, price, observations, addons)"
    ).eq("id", order_id).single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(data, null, 2)
        }
      ],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/list-tables.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.4";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_tables_default = defineTool5({
  name: "list_tables",
  title: "Listar mesas",
  description: "Lista as mesas do restaurante do usu\xE1rio logado, com nome, capacidade e status.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("Quantidade m\xE1xima de mesas (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit = 50 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("mesas").select("id, name, capacity, status, qr_code_url, created_at").order("name", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length > 0 ? JSON.stringify(data, null, 2) : "Nenhuma mesa encontrada."
        }
      ],
      structuredContent: { tables: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-restaurant-profile.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.105.4";
function supabaseForUser6(ctx) {
  return createClient6(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_restaurant_profile_default = defineTool6({
  name: "get_restaurant_profile",
  title: "Perfil do restaurante",
  description: "Retorna os dados b\xE1sicos do restaurante vinculado ao usu\xE1rio logado, como nome, slug, telefone e endere\xE7o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("restaurants").select(
      "id, name, slug, phone, address, city, state, logo_url, primary_color, is_active, created_at"
    ).single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(data, null, 2)
        }
      ],
      structuredContent: { restaurant: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jyrfjvyeikhqpuwcvdff";
var mcp_default = defineMcp({
  name: "pubfy-mcp",
  title: "Pubfy",
  version: "0.1.0",
  instructions: "Ferramentas do Pubfy para restaurantes. Use-as para consultar produtos, categorias, pedidos, mesas e perfil do restaurante do usu\xE1rio autenticado. Todos os dados s\xE3o filtrados pelo restaurante vinculado ao usu\xE1rio via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_products_default,
    list_categories_default,
    list_orders_default,
    get_order_details_default,
    list_tables_default,
    get_restaurant_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
