// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Falha de configuração é detectada de forma não fatal: o bundle continua
// carregando para que `main.tsx` consiga mostrar uma tela clara de erro em
// vez de travar o loader inicial. Qualquer chamada real ao Supabase com o
// stub abaixo retorna erro de auth/rede, mas o app exibe a tela de
// configuração antes disso.
export const supabaseConfigError: Error | null =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? new Error(
        "Supabase environment variables are not configured. Configure VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY no painel do Lovable em Project Settings > Environment.",
      )
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://missing-env.supabase.invalid",
  SUPABASE_PUBLISHABLE_KEY || "missing-anon-key",
);
